#ifndef INCLUDE_SRC_COLORS_H_
#define INCLUDE_SRC_COLORS_H_

#include <raylib.h>
#include "lib/clay.h"

#define CONV_COLOR_RAYLIB_CLAY(rl) (Clay_Color){rl.r, rl.g, rl.b, rl.a}

#define SLATE (Color){43, 41, 51, 255}

#define C_LIGHTGRAY  CONV_COLOR_RAYLIB_CLAY(LIGHTGRAY)
#define C_GRAY       CONV_COLOR_RAYLIB_CLAY(GRAY)
#define C_DARKGRAY   CONV_COLOR_RAYLIB_CLAY(DARKGRAY)
#define C_YELLOW     CONV_COLOR_RAYLIB_CLAY(YELLOW)
#define C_GOLD       CONV_COLOR_RAYLIB_CLAY(GOLD)
#define C_ORANGE     CONV_COLOR_RAYLIB_CLAY(ORANGE)
#define C_PINK       CONV_COLOR_RAYLIB_CLAY(PINK)
#define C_RED        CONV_COLOR_RAYLIB_CLAY(RED)
#define C_MAROON     CONV_COLOR_RAYLIB_CLAY(MAROON)
#define C_GREEN      CONV_COLOR_RAYLIB_CLAY(GREEN)
#define C_LIME       CONV_COLOR_RAYLIB_CLAY(LIME)
#define C_DARKGREEN  CONV_COLOR_RAYLIB_CLAY(DARKGREEN)
#define C_SKYBLUE    CONV_COLOR_RAYLIB_CLAY(SKYBLUE)
#define C_BLUE       CONV_COLOR_RAYLIB_CLAY(BLUE)
#define C_DARKBLUE   CONV_COLOR_RAYLIB_CLAY(DARKBLUE)
#define C_PURPLE     CONV_COLOR_RAYLIB_CLAY(PURPLE)
#define C_VIOLET     CONV_COLOR_RAYLIB_CLAY(VIOLET)
#define C_DARKPURPLE CONV_COLOR_RAYLIB_CLAY(DARKPURPLE)
#define C_BEIGE      CONV_COLOR_RAYLIB_CLAY(BEIGE)
#define C_BROWN      CONV_COLOR_RAYLIB_CLAY(BROWN)
#define C_DARKBROWN  CONV_COLOR_RAYLIB_CLAY(DARKBROWN)

#define C_WHITE      CONV_COLOR_RAYLIB_CLAY(WHITE)
#define C_BLACK      CONV_COLOR_RAYLIB_CLAY(BLACK)
#define C_BLANK      CONV_COLOR_RAYLIB_CLAY(BLANK)
#define C_MAGENTA    CONV_COLOR_RAYLIB_CLAY(MAGENTA)
#define C_RAYWHITE   CONV_COLOR_RAYLIB_CLAY(RAYWHITE)

#define C_SLATE CONV_COLOR_RAYLIB_CLAY(SLATE)

#endif  // INCLUDE_SRC_COLORS_H_
